### ISSUE TITLE
Allow config change of heading font weight

### ISSUE THREAD

**Issue by wizhou** [wizhou/coeur-de-fer#5]
Inside `typography/headings`, the heading font weight is set by default to `bold`. A more clever way would be to set it up into `config.less`.

````less 
each(range(6), {
  h@{value} {
    margin-top: 1em;
    font-weight: bold; // Here is problematic
  }
});
````
